### ISSUE TITLE
Parameter isn't recognized in a filter using the language function

### ISSUE THREAD

**Issue by RoderickvanderWeerdt** [CLARIAH/grlc#230] opened 2019-10-08 14:36 UTC
When a filter that uses the `LANG` function is used in a query grlc doesn't recognize the parameter in that line ([example](http://grlc.io/api/RoderickvanderWeerdt/grlc_test_data/commit/78fcfce17ac3dbcd369ebbbbbd3633558d4fa5a2#/occupationalCoding/get_retrieve_hisco_with_regex_and_language_par)).

The same query does work when there isn't a filter with the language function ([example](http://grlc.io/api/RoderickvanderWeerdt/grlc_test_data/commit/78fcfce17ac3dbcd369ebbbbbd3633558d4fa5a2#/occupationalCoding/get_retrieve_hisco_with_regex)), or when the language tag in the function is not a variable ([example](http://grlc.io/api/RoderickvanderWeerdt/grlc_test_data/commit/78fcfce17ac3dbcd369ebbbbbd3633558d4fa5a2#/occupationalCoding/get_retrieve_hisco_with_regex_and_language)).

**Comment by c-martinez** [comment] 2020-05-12 21:36
It seems like the issue is that (according to rdflib) in this query:
```SPARQL
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hisco-code: <https://iisg.amsterdam/resource/hisco/code/hisco/>

SELECT ?names ?code WHERE {
  ?s schema:occupationalCategory ?category .
  ?category schema:codeValue ?code .
  ?s schema:name ?names .
  FILTER(LANG(?names) = ?_lan).
  FILTER(regex(?names, ?_name, "i")).
} 
ORDER BY ASC(?names)
LIMIT 1```
`?_lan` is not a variable, and grlc tries to replace variable in the query.

The following query, should allow for `?_lan` to be a variable

```SPARQL
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hisco-code: <https://iisg.amsterdam/resource/hisco/code/hisco/>

SELECT ?names ?code WHERE {
  ?s schema:occupationalCategory ?category .
  ?category schema:codeValue ?code .
  ?s schema:name ?names .
  ?_lan a rdfs:Literal.
  FILTER(LANG(?names) = ?_lan).
  FILTER(regex(?names, ?_name, "i")).
} 
ORDER BY ASC(?names)
LIMIT 1
```
and because a language should always be a `rdfs:Literal` this should work.

If this works for you, we can close this issue.

**Comment by c-martinez** [comment] 2021-05-16 19:28
Closing this issue. If the proposed solution does not work, please re-open it.

**Closed by c-martinez** 2021-05-16 19:28 UTC
Labels: bug
