### ISSUE TITLE
GUI not working when grlc is not on root path

### ISSUE THREAD

**Issue by tkuhn** [CLARIAH/grlc#247] opened 2020-03-02 13:58 UTC
When grlc is not configured on root path like http://mydomain.com/ but on a sub-path like http://mydomain.com/mypath/ then the GUI doesn't seem to work. The API itself doesn't seem to be affected and calls to it answer correctly, but the user interface doesn't work.

Here is a live instance that shows this problem: https://openphacts.cs.man.ac.uk/nanopub/grlc/api/local/local

As this example shows, the actual API works correctly: https://openphacts.cs.man.ac.uk/nanopub/grlc/api/local/local/get_all_users

**Comment by c-martinez** [comment] 2020-03-08 15:27
Hi @tkuhn -- thanks for reporting this.

It looks like the issue is that grlc GUI is not able to locate some javascript files when it is loaded from a sub-path. I've added a fix in `dev` branch, which should fix this issue.

By the way, the `dev` branch also has some recent updates, where you can load a local API using the `/api-local` endpoint. So something like this: https://openphacts.cs.man.ac.uk/nanopub/grlc/api-local/ should work.

**Comment by tkuhn** [comment] 2020-03-09 09:43
Hi thanks!

**Comment by c-martinez** [comment] 2020-03-09 09:50
That seems to be unrelated. I am guessing you are using the docker image?

**Comment by tkuhn** [comment] 2020-03-09 10:10
Yes, that was unrelated!

Haven't managed to set it up under a path though yet. The openphacts server is itself not under my control, and I don't know exactly how it was set up there.

Do I need to include the path in GRLC_SERVER_NAME?

**Comment by c-martinez** [comment] 2020-03-09 10:50
No, GRLC_SERVER_NAME should only include the server's domain name (GRLC_SERVER_NAME=openphacts.cs.man.ac.uk in this case).

That is a good point -- depending how the openphacts server is configured, this could have some impact into how the paths get generated.

**Comment by c-martinez** [comment] 2020-03-12 22:14
Hi @tkuhn!

I've updated the `clariah/grlc:dev` image so it should work on a sub-path.

If you are starting the docker image using docker-compose, you should make sure to set up environment variables, for example:

```
  grlc:
    image: clariah/grlc:dev
    environment:
     - DEBUG=true
     - USERMAP_GID=1000
     - USERMAP_UID=1000
     - GRLC_GITHUB_ACCESS_TOKEN=XXXXXXXXXXX
     - GRLC_SERVER_NAME=openphacts.cs.man.ac.uk
```
If this works, can we close this issue?

**Comment by tkuhn** [comment] 2020-03-27 06:40
Getting these errors now:

Mapping UID/GID
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Restarting nginx: nginx.
Reading config file:  /home/grlc/grlc/config.ini
Traceback (most recent call last):
  File "/usr/local/bin/grlc-server", line 11, in <module>
    from grlc.server import app as grlc_app
  File "/usr/local/lib/python3.6/site-packages/grlc/server.py", line 8, in <module>
    import grlc.static as static
  File "/usr/local/lib/python3.6/site-packages/grlc/static.py", line 62, in <module>
    LOG_DEBUG_MODE = config.getboolean('defaults', 'debug')
  File "/usr/local/lib/python3.6/configparser.py", line 829, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/local/lib/python3.6/configparser.py", line 809, in _get_conv
    **kwargs)
  File "/usr/local/lib/python3.6/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/local/lib/python3.6/configparser.py", line 1155, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean:

**Comment by c-martinez** [comment] 2020-03-27 20:08
```
```

**Comment by tkuhn** [comment] 2020-03-29 11:11
Right, I didn't have that. Now it seems to work. But I have to use `/api-local` instead of `/api/local/local`, which means I also have to change the code in my Tapas interface. Could this maybe be made backwards-compatible (so still supporting `/api/local/local)? Otherwise, it's difficult to implement in Tapas in a way that works with both branches of grlc...

**Comment by c-martinez** [comment] 2020-04-01 06:40
Yes, we are moving from `/api/local/local` to `/api-local` on the next release, but you are right, backwards compatibility might be a good idea.

"Using Tapas with both branches of grlc" -- do you mean you have two instances, one using the `dev` docker image and one using the `master` image? If that is the case, could you test if this image works for you `image: cmartinez/grlc:dev` before I merge my changes?

**Comment by tkuhn** [comment] 2020-04-01 09:33
Yes, seems to work!

I have just one version of Tapas that connects to grlc instances, defined either in the config or a URL parameter. So, in this situation, Tapas doesn't know what version that service is running, and having to try both `api/local/local` and `api-local` is not optimal. A backwards-compatible solution would be great for this. Or do the move to `api-local` quickly in all versions (and official grlc installations) such that we can abandon the old one right away :)

**Comment by c-martinez** [comment] 2020-04-02 07:19
Great!

Ok -- I think backwards compatibility is a good idea for the next release (no date planned for it yet, but probably before the summer). We will move to `api-local` as the preferred option and eventually get rid of the `api/local/local` option.

I'll close this issue.

**Closed by c-martinez** 2020-04-02 07:19 UTC

**Comment by c-martinez** [comment] 2020-05-12 21:53
Hi @tkuhn -- just to let you know that the official grlc instance and latest docker hub images are all using the new api (`/api-local`). We will remove the `api/local/local` option in a future release (probably end of the year).

**Comment by tkuhn** [comment] 2020-05-14 07:09
Thanks! I will then make the switch in my code in the coming months.

**Comment by tkuhn** [comment] 2020-06-26 14:04
Very helpful that `api/local/local` is still working for backwards compatibility. However, I realized that the JSON definition that was at `.../spec` is now at `.../swagger`. Would it be possible to make this backwards compatible too, i.e. serve the same JSON at both paths?

**Comment by c-martinez** [comment] 2020-06-26 18:50
Sure I have created an issue for it :-)
